### ISSUE TITLE
convert the list into an awesome-list

### ISSUE THREAD

**Issue by rcmorano** [Scanate/EthList#12]
Just as a suggestion, your nice list of resources reminded me that I found some other awesome-ethereum lists around:

* https://github.com/vinsgo/awesome-ethereum
* https://github.com/toadkicker/awesome-ethereum
* https://github.com/void4/awesome-ethereum
* https://github.com/btomashvili/awesome-ethereum

Else, they might be useful as inspiration :)

**Comment by philtable** [comment]
Thanks, looks cool!
